---
title: "R Notebook"
knit: (function(input_file, encoding) { out_dir <- 'docs'; rmarkdown::render(input_file,
  encoding=encoding, output_file=file.path(dirname(input_file), out_dir, 'index.html'))})
output:
  html_document:
    df_print: paged
---

Install packages
```{r}
install.packages("tidyverse")
install.packages("dplyr")
install.packages("moments")
install.packages("ggplot2")
install.packages("esquisse")

```

Load packages
```{r}
library(tidyverse)
library(dplyr)
library(moments)
library(ggplot2)
library(esquisse)
```

Load data
```{r}
df <- read_csv("../Data/rural_atlas_merged.csv")
```

Inspect data
```{r}
View(df)
head(df)
str(df)
nrow(df)
ncol(df)
names(df)
```


```{r}
# i) Sample mean for PerCapitaInc:
print(sample_mean_PerCapitaInc <- mean(df$PerCapitaInc, na.rm = TRUE))
```

```{r}
# ii) Sample Standard Deviation PerCapitaInc:
print(sample_standard_deviation_PerCapitalInc <- sd(df$PerCapitaInc, na.rm = TRUE))
```
     

```{r}
# iii) Sample skewness PerCapitaInc (package: moments):
print(sample_skewness_PerCapitaInc <- skewness(df$PerCapitaInc, na.rm = TRUE))
```

```{r}
# iv) Sample kurtosis and (v) PerCapitaInc (package: moments):
print(sample_kurtosis_PerCapitaInc <- kurtosis(df$PerCapitaInc, na.rm = TRUE))
```

```{r}
# v) Sample size for per capita income (variable name is "PerCapitaInc"):
print(n <- sample_size_PerCapitaInc <- summarize(df, n()))
```
     

```{r}
# Min:
print(min <- min(df$PerCapitaInc, na.rm = TRUE))
# Max:
print(max <- max(df$PerCapitaInc, na.rm = TRUE))
```


### Per Capita Income

Density
```{r}
#ggplot2 is a data visualization package of R that provides a general scheme for data visualization.
ggplot(data = df) +  
  geom_density(mapping = aes(x = (df$PerCapitaInc)))
 
```

### 4e. Metro2013 

Scatter Plot
```{r}
#ggplot2 is a data visualization package of R that provides a general scheme for data visualization.
ggplot(data = df) +  
  geom_point(mapping = aes(x = PerCapitaInc, y = Metro2013), alpha=0.1, color="black") 

```


```{r}
#Restricting the sample...Sub-setting is a very important component of data management and there are several ways that one can subset data in R.
subset_of_data <- subset(df, Metro2013 == 1)
```



```{r}
# Mean
# i.
print(sample_mean_subset_PerCapInc <- mean(subset_of_data$PerCapitaInc, na.rm = TRUE))

# Mean
# i.
print(sample_mean_subset_UnempRate2013 <- mean(subset_of_data$UnempRate2013, na.rm = TRUE))

```



```{r}
# sd for PerCapitaInc
# ii.
print(SD_subset_Metro2013 <- sd(subset_of_data$PerCapitaInc, na.rm = TRUE))

# sd for UnEmpRate2013
# ii.
print(SD_UnempRate2013_subset_Metro2013 <- sd(subset_of_data$UnempRate2013, na.rm = TRUE))

```


```{r}
# sample size for UnEmpRate2013 n = 1236
print(n <- PerCapitaInc <- summarize(subset_of_data, n()))

# sample size for PerCapitaInc
# print(n <- sample_size_PerCapitaInc <- summarize(subset_of_data, n()))

```




```{r}
# g.)
NonMetro_subset_of_data <- subset(df, Metro2013 == 0)

```

