---
title: "Final Project"
author: "Lorenzo Bartolo"

output:
  pdf_document: default
  html_document: default
    
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(tidy.opts = list(width.cutoff = 60), tidy = TRUE, echo = TRUE)

# List of packages you want to install -- separated with a comma and surrounded in "quotes" 
packages <- c("tidyverse", "dplyr", "moments", "lmtest", "sandwich", "stringr", "readr", "here", "ggplot2", "modelr", "MASS", "knitr", "formatR", "car", "AER", "plm", "stargazer", "readxl","haven")

# Installs packages
installed_packages <- packages %in% rownames(installed.packages())
if (any(installed_packages == FALSE)) {
  install.packages(packages[!installed_packages])
}

# Loads packages
invisible(lapply(packages, library, character.only = TRUE))

```

```{r}
# Load in data
health_inequality_full_covariates <- read_dta("../Data/health_ineq_replication_dataonly/data/derived/final_covariates/cty_full_covariates.dta")
```


```{r}
sink(file = "summary.txt")

str(health_inequality_full_covariates)

sink()
```

