---
output:
  pdf_document: default
  html_document: default
---


# Plots:

## Income and Mortality
```{r}
# Plot Income and Mortality 
plot(x = data_table_16$indv_inc, 
     y = data_table_16$mortrate, 
     xlab = "Income",
     ylab = "Mortality Rate",
     main = "Mortality Rates and Income",
     col = "steelblue")
# Add trend line
abline(Mortality.model.1, col = "red")
```


## Income and Life Expectancy
```{r}
# Plot Income and Mortality 
plot(x = data_table_16$indv_inc, 
     y = data_table_16$age_at_d, 
     xlab = "Income",
     ylab = "Age at Death",
     main = "Life Expectancy and Income",
     col = "steelblue")
# Add trend line
abline(Life.Expect.model.1, col = "red")
```



## Income Percentile and Mortality Rate
```{r}
# Plot Income Percentile and Mortality Rate 
plot(x = data_table_16$indv_pctile, 
     y = data_table_16$mortrate, 
     xlab = "Income Percentile",
     ylab = "Mortality Rate",
     main = "Mortality Rates and Income Percentile",
     col = "steelblue")
# Add trend line
abline(Mortality.model.1, col = "red")
```



## Income Percentile and Life Expectancy
```{r}
plot(x = data_table_16$indv_pctile, 
     y = data_table_16$age_at_d, 
     xlab = "Income Percentile",
     ylab = "Age at Death",
     main = "Income Percentile and Life Expectancy",
     col = "steelblue")
# Add trend line
abline(Life.Expect.model.1, col = "red")
```



# Models:

## Mortality Rate Model 1
```{r}
Mortality.model.1 <- lm(data_table_16$mortrate ~ data_table_16$indv_inc)
summary(Mortality.model.1)
coeftest(Mortality.model.1, vcov. = vcovHC, type = "HC1")
```


## Mortality Rate Model 2
```{r}
Mortality.model.2 <- lm(data_table_16$mortrate ~ data_table_16$indv_inc + data_table_16$indv_pctile)
summary(Mortality.model.2)
coeftest(Mortality.model.2, vcov. = vcovHC, type = "HC1")
```


## Mortality Rate Model 3
```{r}
Mortality.model.3 <- lm(data_table_16$mortrate ~ data_table_16$indv_inc + data_table_16$indv_pctile + data_table_16$age_at_d)
summary(Mortality.model.3)
coeftest(Mortality.model.3, vcov. = vcovHC, type = "HC1")
```

